---
title: "Homework 5"
author: "Murrel Pereira"
date: "11/10/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width=6,
  fig.asp=.6,
  out.width ="90%"
)

theme_set(theme_minimal() +theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete=scale_fill_viridis_d

```

## Problem 1

Read in the data.

```{r}
homicide_df =
  read_csv("homicide_data/homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"
    ),
    city_state = str_c(city, state, sep = "_")
  ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa_AL") 
  
```

Look at this a bit

```{r}
aggregate_df =
homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  ) %>% 
  arrange(hom_unsolved)
```

Can I do a prop test for a single city?

```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved),
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)
) %>% 
  broom::tidy()
```

Try to iterate....

```{r}
results_df =
aggregate_df %>% 
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x=prop_tests, ~broom::tidy(.x))
  ) %>% select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high) %>% 
  arrange(desc(estimate))
  
  
```

```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1))
  
```

## Problem 2

Create tidy dataset
```{r}

path_df = 
tibble(
  path = list.files("lda_data")
) %>% 
  mutate(
    path = str_c("lda_data/",path),
    obs = map(path, read_csv),
    treatment = case_when(
      str_detect(path, "con") ~ "control",
      str_detect(path, "exp") ~ "experimental"
    ),
    subject = substr(path, start = 10, stop =15),
    subject = as.factor(subject),
    treatment = as.factor(treatment)
  ) %>% 
  unnest(obs) %>% 
  pivot_longer(week_1:week_8,
              names_to ="week",
              names_prefix = "week_",
              values_to = "observations")

```

Create spaghetti plot
```{r}
ggplot(path_df, aes(x = week, y = observations, group = subject, color = treatment)) + geom_point() + geom_line() 
```

## Problem 3

```{r}

```

